export default [
  {
    obsolete: false,
    iso2: "AF",
    iso3: "AFG",
    iso4: null,
    isoNum: "004",
    name: { FRA: "Afghanistan" },
  },
  {
    obsolete: false,
    iso2: "ZA",
    iso3: "ZAF",
    iso4: null,
    isoNum: "710",
    name: { FRA: "Afrique du Sud" },
  },
  {
    obsolete: false,
    iso2: "AX",
    iso3: "ALA",
    iso4: null,
    isoNum: "248",
    name: { FRA: "Åland" },
  },
  {
    obsolete: false,
    iso2: "AL",
    iso3: "ALB",
    iso4: null,
    isoNum: "008",
    name: { FRA: "Albanie" },
  },
  {
    obsolete: false,
    iso2: "DZ",
    iso3: "DZA",
    iso4: null,
    isoNum: "012",
    name: { FRA: "Algérie" },
  },
  {
    obsolete: false,
    iso2: "DE",
    iso3: "DEU",
    iso4: null,
    isoNum: "276",
    name: { FRA: "Allemagne" },
  },
  {
    obsolete: false,
    iso2: "AD",
    iso3: "AND",
    iso4: null,
    isoNum: "020",
    name: { FRA: "Andorre" },
  },
  {
    obsolete: false,
    iso2: "AO",
    iso3: "AGO",
    iso4: null,
    isoNum: "024",
    name: { FRA: "Angola" },
  },
  {
    obsolete: false,
    iso2: "AI",
    iso3: "AIA",
    iso4: null,
    isoNum: "660",
    name: { FRA: "Anguilla" },
  },
  {
    obsolete: false,
    iso2: "AQ",
    iso3: "ATA",
    iso4: null,
    isoNum: "010",
    name: { FRA: "Antarctique" },
  },
  {
    obsolete: false,
    iso2: "AG",
    iso3: "ATG",
    iso4: null,
    isoNum: "028",
    name: { FRA: "Antigua et Barbuda" },
  },
  {
    obsolete: true,
    iso2: "AN",
    iso3: "ANT",
    iso4: "ANHH",
    isoNum: "530",
    name: { FRA: "Antilles néerlandaises" },
  },
  {
    obsolete: false,
    iso2: "SA",
    iso3: "SAU",
    iso4: null,
    isoNum: "682",
    name: { FRA: "Arabie saoudite" },
  },
  {
    obsolete: false,
    iso2: "AR",
    iso3: "ARG",
    iso4: null,
    isoNum: "032",
    name: { FRA: "Argentine" },
  },
  {
    obsolete: false,
    iso2: "AM",
    iso3: "ARM",
    iso4: null,
    isoNum: "051",
    name: { FRA: "Arménie" },
  },
  {
    obsolete: false,
    iso2: "AW",
    iso3: "ABW",
    iso4: null,
    isoNum: "533",
    name: { FRA: "Aruba" },
  },
  {
    obsolete: false,
    iso2: "AU",
    iso3: "AUS",
    iso4: null,
    isoNum: "036",
    name: { FRA: "Australie" },
  },
  {
    obsolete: false,
    iso2: "AT",
    iso3: "AUT",
    iso4: null,
    isoNum: "040",
    name: { FRA: "Autriche" },
  },
  {
    obsolete: false,
    iso2: "AZ",
    iso3: "AZE",
    iso4: null,
    isoNum: "031",
    name: { FRA: "Azerbaïdjan" },
  },
  {
    obsolete: false,
    iso2: "BS",
    iso3: "BHS",
    iso4: null,
    isoNum: "044",
    name: { FRA: "Bahamas" },
  },
  {
    obsolete: false,
    iso2: "BH",
    iso3: "BHR",
    iso4: null,
    isoNum: "048",
    name: { FRA: "Bahreïn" },
  },
  {
    obsolete: false,
    iso2: "BD",
    iso3: "BGD",
    iso4: null,
    isoNum: "050",
    name: { FRA: "Bangladesh" },
  },
  {
    obsolete: false,
    iso2: "BB",
    iso3: "BRB",
    iso4: null,
    isoNum: "052",
    name: { FRA: "Barbade" },
  },
  {
    obsolete: false,
    iso2: "BY",
    iso3: "BLR",
    iso4: null,
    isoNum: "112",
    name: { FRA: "Bélarus" },
  },
  {
    obsolete: false,
    iso2: "BE",
    iso3: "BEL",
    iso4: null,
    isoNum: "056",
    name: { FRA: "Belgique" },
  },
  {
    obsolete: false,
    iso2: "BZ",
    iso3: "BLZ",
    iso4: null,
    isoNum: "084",
    name: { FRA: "Belize" },
  },
  {
    obsolete: false,
    iso2: "BJ",
    iso3: "BEN",
    iso4: null,
    isoNum: "204",
    name: { FRA: "Bénin" },
  },
  {
    obsolete: false,
    iso2: "BM",
    iso3: "BMU",
    iso4: null,
    isoNum: "060",
    name: { FRA: "Bermudes" },
  },
  {
    obsolete: false,
    iso2: "BT",
    iso3: "BTN",
    iso4: null,
    isoNum: "064",
    name: { FRA: "Bhoutan" },
  },
  {
    obsolete: true,
    iso2: "BY",
    iso3: "BYS",
    iso4: "BYAA",
    isoNum: "112",
    name: { FRA: "Biélorussie" },
  },
  {
    obsolete: false,
    iso2: "BO",
    iso3: "BOL",
    iso4: null,
    isoNum: "068",
    name: { FRA: "Bolivie" },
  },
  {
    obsolete: false,
    iso2: "BQ",
    iso3: "BES",
    iso4: null,
    isoNum: "535",
    name: { FRA: "Pays-Bas caribéens" },
  },
  {
    obsolete: false,
    iso2: "BA",
    iso3: "BIH",
    iso4: null,
    isoNum: "070",
    name: { FRA: "Bosnie-Herzégovine" },
  },
  {
    obsolete: false,
    iso2: "BW",
    iso3: "BWA",
    iso4: null,
    isoNum: "072",
    name: { FRA: "Botswana" },
  },
  {
    obsolete: false,
    iso2: "BV",
    iso3: "BVT",
    iso4: null,
    isoNum: "074",
    name: { FRA: "Île Bouvet" },
  },
  {
    obsolete: false,
    iso2: "BR",
    iso3: "BRA",
    iso4: null,
    isoNum: "076",
    name: { FRA: "Brésil" },
  },
  {
    obsolete: false,
    iso2: "BN",
    iso3: "BRN",
    iso4: null,
    isoNum: "096",
    name: { FRA: "Brunei" },
  },
  {
    obsolete: false,
    iso2: "BG",
    iso3: "BGR",
    iso4: null,
    isoNum: "100",
    name: { FRA: "Bulgarie" },
  },
  {
    obsolete: false,
    iso2: "BF",
    iso3: "BFA",
    iso4: null,
    isoNum: "854",
    name: { FRA: "Burkina Faso" },
  },
  {
    obsolete: false,
    iso2: "BI",
    iso3: "BDI",
    iso4: null,
    isoNum: "108",
    name: { FRA: "Burundi" },
  },
  {
    obsolete: false,
    iso2: "CV",
    iso3: "CPV",
    iso4: null,
    isoNum: "132",
    name: { FRA: "Cap-Vert" },
  },
  {
    obsolete: false,
    iso2: "KY",
    iso3: "CYM",
    iso4: null,
    isoNum: "136",
    name: { FRA: "Îles Caïmans" },
  },
  {
    obsolete: false,
    iso2: "KH",
    iso3: "KHM",
    iso4: null,
    isoNum: "116",
    name: { FRA: "Cambodge" },
  },
  {
    obsolete: false,
    iso2: "CM",
    iso3: "CMR",
    iso4: null,
    isoNum: "120",
    name: { FRA: "Cameroun" },
  },
  {
    obsolete: false,
    iso2: "CA",
    iso3: "CAN",
    iso4: null,
    isoNum: "124",
    name: { FRA: "Canada" },
  },
  {
    obsolete: false,
    iso2: "CF",
    iso3: "CAF",
    iso4: null,
    isoNum: "140",
    name: { FRA: "République centrafricaine" },
  },
  {
    obsolete: false,
    iso2: "CL",
    iso3: "CHL",
    iso4: null,
    isoNum: "152",
    name: { FRA: "Chili" },
  },
  {
    obsolete: false,
    iso2: "CN",
    iso3: "CHN",
    iso4: null,
    isoNum: "156",
    name: { FRA: "Chine" },
  },
  {
    obsolete: false,
    iso2: "CX",
    iso3: "CXR",
    iso4: null,
    isoNum: "162",
    name: { FRA: "Île Christmas" },
  },
  {
    obsolete: false,
    iso2: "CY",
    iso3: "CYP",
    iso4: null,
    isoNum: "196",
    name: { FRA: "Chypre" },
  },
  {
    obsolete: false,
    iso2: "CC",
    iso3: "CCK",
    iso4: null,
    isoNum: "166",
    name: { FRA: "Îles Cocos" },
  },
  {
    obsolete: false,
    iso2: "CO",
    iso3: "COL",
    iso4: null,
    isoNum: "170",
    name: { FRA: "Colombie" },
  },
  {
    obsolete: false,
    iso2: "KM",
    iso3: "COM",
    iso4: null,
    isoNum: "174",
    name: { FRA: "Comores" },
  },
  {
    obsolete: false,
    iso2: "CG",
    iso3: "COG",
    iso4: null,
    isoNum: "178",
    name: { FRA: "République du Congo" },
  },
  {
    obsolete: false,
    iso2: "CD",
    iso3: "COD",
    iso4: null,
    isoNum: "180",
    name: { FRA: "République démocratique du Congo" },
  },
  {
    obsolete: false,
    iso2: "CK",
    iso3: "COK",
    iso4: null,
    isoNum: "184",
    name: { FRA: "Îles Cook" },
  },
  {
    obsolete: false,
    iso2: "KR",
    iso3: "KOR",
    iso4: null,
    isoNum: "410",
    name: { FRA: "Corée du Sud" },
  },
  {
    obsolete: false,
    iso2: "KP",
    iso3: "PRK",
    iso4: null,
    isoNum: "408",
    name: { FRA: "Corée du Nord" },
  },
  {
    obsolete: false,
    iso2: "CR",
    iso3: "CRI",
    iso4: null,
    isoNum: "188",
    name: { FRA: "Costa Rica" },
  },
  {
    obsolete: false,
    iso2: "CI",
    iso3: "CIV",
    iso4: null,
    isoNum: "384",
    name: { FRA: "Côte d'Ivoire" },
  },
  {
    obsolete: false,
    iso2: "HR",
    iso3: "HRV",
    iso4: null,
    isoNum: "191",
    name: { FRA: "Croatie" },
  },
  {
    obsolete: false,
    iso2: "CU",
    iso3: "CUB",
    iso4: null,
    isoNum: "192",
    name: { FRA: "Cuba" },
  },
  {
    obsolete: false,
    iso2: "CW",
    iso3: "CUW",
    iso4: null,
    isoNum: "531",
    name: { FRA: "Curaçao" },
  },
  {
    obsolete: false,
    iso2: "DK",
    iso3: "DNK",
    iso4: null,
    isoNum: "208",
    name: { FRA: "Danemark" },
  },
  {
    obsolete: false,
    iso2: "DJ",
    iso3: "DJI",
    iso4: null,
    isoNum: "262",
    name: { FRA: "Djibouti" },
  },
  {
    obsolete: false,
    iso2: "DO",
    iso3: "DOM",
    iso4: null,
    isoNum: "214",
    name: { FRA: "République dominicaine" },
  },
  {
    obsolete: false,
    iso2: "DM",
    iso3: "DMA",
    iso4: null,
    isoNum: "212",
    name: { FRA: "Dominique" },
  },
  {
    obsolete: false,
    iso2: "EG",
    iso3: "EGY",
    iso4: null,
    isoNum: "818",
    name: { FRA: "Égypte" },
  },
  {
    obsolete: false,
    iso2: "SV",
    iso3: "SLV",
    iso4: null,
    isoNum: "222",
    name: { FRA: "Salvador" },
  },
  {
    obsolete: false,
    iso2: "AE",
    iso3: "ARE",
    iso4: null,
    isoNum: "784",
    name: { FRA: "Émirats arabes unis" },
  },
  {
    obsolete: false,
    iso2: "EC",
    iso3: "ECU",
    iso4: null,
    isoNum: "218",
    name: { FRA: "Équateur" },
  },
  {
    obsolete: false,
    iso2: "ER",
    iso3: "ERI",
    iso4: null,
    isoNum: "232",
    name: { FRA: "Érythrée" },
  },
  {
    obsolete: false,
    iso2: "ES",
    iso3: "ESP",
    iso4: null,
    isoNum: "724",
    name: { FRA: "Espagne" },
  },
  {
    obsolete: false,
    iso2: "EE",
    iso3: "EST",
    iso4: null,
    isoNum: "233",
    name: { FRA: "Estonie" },
  },
  {
    obsolete: false,
    iso2: "SZ",
    iso3: "SWZ",
    iso4: null,
    isoNum: "748",
    name: { FRA: "Eswatini" },
  },
  {
    obsolete: false,
    iso2: "PS",
    iso3: "PSE",
    iso4: null,
    isoNum: "275",
    name: { FRA: "Palestine" },
  },
  {
    obsolete: false,
    iso2: "US",
    iso3: "USA",
    iso4: null,
    isoNum: "840",
    name: { FRA: "États-Unis" },
  },
  {
    obsolete: false,
    iso2: "ET",
    iso3: "ETH",
    iso4: null,
    isoNum: "231",
    name: { FRA: "Éthiopie" },
  },
  {
    obsolete: false,
    iso2: "FK",
    iso3: "FLK",
    iso4: null,
    isoNum: "238",
    name: { FRA: "Malouines" },
  },
  {
    obsolete: false,
    iso2: "FO",
    iso3: "FRO",
    iso4: null,
    isoNum: "234",
    name: { FRA: "Îles Féroé" },
  },
  {
    obsolete: false,
    iso2: "FJ",
    iso3: "FJI",
    iso4: null,
    isoNum: "242",
    name: { FRA: "Fidji" },
  },
  {
    obsolete: false,
    iso2: "FI",
    iso3: "FIN",
    iso4: null,
    isoNum: "246",
    name: { FRA: "Finlande" },
  },
  {
    obsolete: false,
    iso2: "FR",
    iso3: "FRA",
    iso4: null,
    isoNum: "250",
    name: { FRA: "France" },
  },
  {
    obsolete: false,
    iso2: "GA",
    iso3: "GAB",
    iso4: null,
    isoNum: "266",
    name: { FRA: "Gabon" },
  },
  {
    obsolete: false,
    iso2: "GM",
    iso3: "GMB",
    iso4: null,
    isoNum: "270",
    name: { FRA: "Gambie" },
  },
  {
    obsolete: false,
    iso2: "GE",
    iso3: "GEO",
    iso4: null,
    isoNum: "268",
    name: { FRA: "Géorgie" },
  },
  {
    obsolete: false,
    iso2: "GS",
    iso3: "SGS",
    iso4: null,
    isoNum: "239",
    name: { FRA: "Géorgie du Sud et les îles Sandwich du Sud" },
  },
  {
    obsolete: false,
    iso2: "GH",
    iso3: "GHA",
    iso4: null,
    isoNum: "288",
    name: { FRA: "Ghana" },
  },
  {
    obsolete: false,
    iso2: "GI",
    iso3: "GIB",
    iso4: null,
    isoNum: "292",
    name: { FRA: "Gibraltar" },
  },
  {
    obsolete: false,
    iso2: "GR",
    iso3: "GRC",
    iso4: null,
    isoNum: "300",
    name: { FRA: "Grèce" },
  },
  {
    obsolete: false,
    iso2: "GD",
    iso3: "GRD",
    iso4: null,
    isoNum: "308",
    name: { FRA: "Grenade" },
  },
  {
    obsolete: false,
    iso2: "GL",
    iso3: "GRL",
    iso4: null,
    isoNum: "304",
    name: { FRA: "Groenland" },
  },
  {
    obsolete: false,
    iso2: "GP",
    iso3: "GLP",
    iso4: null,
    isoNum: "312",
    name: { FRA: "Guadeloupe" },
  },
  {
    obsolete: false,
    iso2: "GU",
    iso3: "GUM",
    iso4: null,
    isoNum: "316",
    name: { FRA: "Guam" },
  },
  {
    obsolete: false,
    iso2: "GT",
    iso3: "GTM",
    iso4: null,
    isoNum: "320",
    name: { FRA: "Guatemala" },
  },
  {
    obsolete: false,
    iso2: "GG",
    iso3: "GGY",
    iso4: null,
    isoNum: "831",
    name: { FRA: "Guernesey" },
  },
  {
    obsolete: false,
    iso2: "GN",
    iso3: "GIN",
    iso4: null,
    isoNum: "324",
    name: { FRA: "Guinée" },
  },
  {
    obsolete: false,
    iso2: "GW",
    iso3: "GNB",
    iso4: null,
    isoNum: "624",
    name: { FRA: "Guinée-Bissau" },
  },
  {
    obsolete: false,
    iso2: "GQ",
    iso3: "GNQ",
    iso4: null,
    isoNum: "226",
    name: { FRA: "Guinée équatoriale" },
  },
  {
    obsolete: false,
    iso2: "GY",
    iso3: "GUY",
    iso4: null,
    isoNum: "328",
    name: { FRA: "Guyana" },
  },
  {
    obsolete: false,
    iso2: "GF",
    iso3: "GUF",
    iso4: null,
    isoNum: "254",
    name: { FRA: "Guyane" },
  },
  {
    obsolete: false,
    iso2: "HT",
    iso3: "HTI",
    iso4: null,
    isoNum: "332",
    name: { FRA: "Haïti" },
  },
  {
    obsolete: false,
    iso2: "HM",
    iso3: "HMD",
    iso4: null,
    isoNum: "334",
    name: { FRA: "l'Île Heard-et-Îles MacDonald" },
  },
  {
    obsolete: false,
    iso2: "HN",
    iso3: "HND",
    iso4: null,
    isoNum: "340",
    name: { FRA: "Honduras" },
  },
  {
    obsolete: false,
    iso2: "HK",
    iso3: "HKG",
    iso4: null,
    isoNum: "344",
    name: { FRA: "Hong Kong" },
  },
  {
    obsolete: false,
    iso2: "HU",
    iso3: "HUN",
    iso4: null,
    isoNum: "348",
    name: { FRA: "Hongrie" },
  },
  {
    obsolete: false,
    iso2: "IM",
    iso3: "IMN",
    iso4: null,
    isoNum: "833",
    name: { FRA: "Île de Man" },
  },
  {
    obsolete: true,
    iso2: "PC",
    iso3: "PCI",
    iso4: "PCHH",
    isoNum: "582",
    name: { FRA: "Îles du Pacifique" },
  },
  {
    obsolete: false,
    iso2: "UM",
    iso3: "UMI",
    iso4: null,
    isoNum: "581",
    name: { FRA: "Îles mineures éloignées des États-Unis" },
  },
  {
    obsolete: false,
    iso2: "VG",
    iso3: "VGB",
    iso4: null,
    isoNum: "092",
    name: { FRA: "Îles Vierges britanniques" },
  },
  {
    obsolete: false,
    iso2: "VI",
    iso3: "VIR",
    iso4: null,
    isoNum: "850",
    name: { FRA: "Îles Vierges des États-Unis" },
  },
  {
    obsolete: false,
    iso2: "IN",
    iso3: "IND",
    iso4: null,
    isoNum: "356",
    name: { FRA: "Inde" },
  },
  {
    obsolete: false,
    iso2: "ID",
    iso3: "IDN",
    iso4: null,
    isoNum: "360",
    name: { FRA: "Indonésie" },
  },
  {
    obsolete: false,
    iso2: "IR",
    iso3: "IRN",
    iso4: null,
    isoNum: "364",
    name: { FRA: "Iran" },
  },
  {
    obsolete: false,
    iso2: "IQ",
    iso3: "IRQ",
    iso4: null,
    isoNum: "368",
    name: { FRA: "Irak" },
  },
  {
    obsolete: false,
    iso2: "IE",
    iso3: "IRL",
    iso4: null,
    isoNum: "372",
    name: { FRA: "Irlande" },
  },
  {
    obsolete: false,
    iso2: "IS",
    iso3: "ISL",
    iso4: null,
    isoNum: "352",
    name: { FRA: "Islande" },
  },
  {
    obsolete: false,
    iso2: "IL",
    iso3: "ISR",
    iso4: null,
    isoNum: "376",
    name: { FRA: "Israël" },
  },
  {
    obsolete: false,
    iso2: "IT",
    iso3: "ITA",
    iso4: null,
    isoNum: "380",
    name: { FRA: "Italie" },
  },
  {
    obsolete: false,
    iso2: "JM",
    iso3: "JAM",
    iso4: null,
    isoNum: "388",
    name: { FRA: "Jamaïque" },
  },
  {
    obsolete: false,
    iso2: "JP",
    iso3: "JPN",
    iso4: null,
    isoNum: "392",
    name: { FRA: "Japon" },
  },
  {
    obsolete: false,
    iso2: "JE",
    iso3: "JEY",
    iso4: null,
    isoNum: "832",
    name: { FRA: "Jersey" },
  },
  {
    obsolete: false,
    iso2: "JO",
    iso3: "JOR",
    iso4: null,
    isoNum: "400",
    name: { FRA: "Jordanie" },
  },
  {
    obsolete: false,
    iso2: "KZ",
    iso3: "KAZ",
    iso4: null,
    isoNum: "398",
    name: { FRA: "Kazakhstan" },
  },
  {
    obsolete: false,
    iso2: "KE",
    iso3: "KEN",
    iso4: null,
    isoNum: "404",
    name: { FRA: "Kenya" },
  },
  {
    obsolete: false,
    iso2: "KG",
    iso3: "KGZ",
    iso4: null,
    isoNum: "417",
    name: { FRA: "Kirghizistan" },
  },
  {
    obsolete: false,
    iso2: "KI",
    iso3: "KIR",
    iso4: null,
    isoNum: "296",
    name: { FRA: "Kiribati" },
  },
  {
    obsolete: false,
    iso2: "XK",
    iso3: "XXK",
    iso4: null,
    isoNum: null,
    name: { FRA: "Kosovo" },
  },
  {
    obsolete: false,
    iso2: "KW",
    iso3: "KWT",
    iso4: null,
    isoNum: "414",
    name: { FRA: "Koweït" },
  },
  {
    obsolete: false,
    iso2: "LA",
    iso3: "LAO",
    iso4: null,
    isoNum: "418",
    name: { FRA: "Laos" },
  },
  {
    obsolete: false,
    iso2: "LS",
    iso3: "LSO",
    iso4: null,
    isoNum: "426",
    name: { FRA: "Lesotho" },
  },
  {
    obsolete: false,
    iso2: "LV",
    iso3: "LVA",
    iso4: null,
    isoNum: "428",
    name: { FRA: "Lettonie" },
  },
  {
    obsolete: false,
    iso2: "LB",
    iso3: "LBN",
    iso4: null,
    isoNum: "422",
    name: { FRA: "Liban" },
  },
  {
    obsolete: false,
    iso2: "LR",
    iso3: "LBR",
    iso4: null,
    isoNum: "430",
    name: { FRA: "Liberia" },
  },
  {
    obsolete: false,
    iso2: "LY",
    iso3: "LBY",
    iso4: null,
    isoNum: "434",
    name: { FRA: "Libye" },
  },
  {
    obsolete: false,
    iso2: "LI",
    iso3: "LIE",
    iso4: null,
    isoNum: "438",
    name: { FRA: "Liechtenstein" },
  },
  {
    obsolete: false,
    iso2: "LT",
    iso3: "LTU",
    iso4: null,
    isoNum: "440",
    name: { FRA: "Lituanie" },
  },
  {
    obsolete: false,
    iso2: "LU",
    iso3: "LUX",
    iso4: null,
    isoNum: "442",
    name: { FRA: "Luxembourg" },
  },
  {
    obsolete: false,
    iso2: "MO",
    iso3: "MAC",
    iso4: null,
    isoNum: "446",
    name: { FRA: "Macao" },
  },
  {
    obsolete: false,
    iso2: "MG",
    iso3: "MDG",
    iso4: null,
    isoNum: "450",
    name: { FRA: "Madagascar" },
  },
  {
    obsolete: false,
    iso2: "MY",
    iso3: "MYS",
    iso4: null,
    isoNum: "458",
    name: { FRA: "Malaisie" },
  },
  {
    obsolete: false,
    iso2: "MW",
    iso3: "MWI",
    iso4: null,
    isoNum: "454",
    name: { FRA: "Malawi" },
  },
  {
    obsolete: false,
    iso2: "MV",
    iso3: "MDV",
    iso4: null,
    isoNum: "462",
    name: { FRA: "Maldives" },
  },
  {
    obsolete: false,
    iso2: "ML",
    iso3: "MLI",
    iso4: null,
    isoNum: "466",
    name: { FRA: "Mali" },
  },
  {
    obsolete: false,
    iso2: "MT",
    iso3: "MLT",
    iso4: null,
    isoNum: "470",
    name: { FRA: "Malte" },
  },
  {
    obsolete: false,
    iso2: "MP",
    iso3: "MNP",
    iso4: null,
    isoNum: "580",
    name: { FRA: "Îles Mariannes du Nord" },
  },
  {
    obsolete: false,
    iso2: "MA",
    iso3: "MAR",
    iso4: null,
    isoNum: "504",
    name: { FRA: "Maroc" },
  },
  {
    obsolete: false,
    iso2: "MH",
    iso3: "MHL",
    iso4: null,
    isoNum: "584",
    name: { FRA: "Îles Marshall" },
  },
  {
    obsolete: false,
    iso2: "MQ",
    iso3: "MTQ",
    iso4: null,
    isoNum: "474",
    name: { FRA: "Martinique" },
  },
  {
    obsolete: false,
    iso2: "MU",
    iso3: "MUS",
    iso4: null,
    isoNum: "480",
    name: { FRA: "Maurice" },
  },
  {
    obsolete: false,
    iso2: "MR",
    iso3: "MRT",
    iso4: null,
    isoNum: "478",
    name: { FRA: "Mauritanie" },
  },
  {
    obsolete: false,
    iso2: "YT",
    iso3: "MYT",
    iso4: null,
    isoNum: "175",
    name: { FRA: "Mayotte" },
  },
  {
    obsolete: false,
    iso2: "MX",
    iso3: "MEX",
    iso4: null,
    isoNum: "484",
    name: { FRA: "Mexique" },
  },
  {
    obsolete: false,
    iso2: "FM",
    iso3: "FSM",
    iso4: null,
    isoNum: "583",
    name: { FRA: "Micronésie" },
  },
  {
    obsolete: false,
    iso2: "MD",
    iso3: "MDA",
    iso4: null,
    isoNum: "498",
    name: { FRA: "Moldavie" },
  },
  {
    obsolete: false,
    iso2: "MC",
    iso3: "MCO",
    iso4: null,
    isoNum: "492",
    name: { FRA: "Monaco" },
  },
  {
    obsolete: false,
    iso2: "MN",
    iso3: "MNG",
    iso4: null,
    isoNum: "496",
    name: { FRA: "Mongolie" },
  },
  {
    obsolete: false,
    iso2: "ME",
    iso3: "MNE",
    iso4: null,
    isoNum: "499",
    name: { FRA: "Monténégro" },
  },
  {
    obsolete: false,
    iso2: "MS",
    iso3: "MSR",
    iso4: null,
    isoNum: "500",
    name: { FRA: "Montserrat" },
  },
  {
    obsolete: false,
    iso2: "MZ",
    iso3: "MOZ",
    iso4: null,
    isoNum: "508",
    name: { FRA: "Mozambique" },
  },
  {
    obsolete: false,
    iso2: "MM",
    iso3: "MMR",
    iso4: null,
    isoNum: "104",
    name: { FRA: "Birmanie" },
  },
  {
    obsolete: false,
    iso2: "NA",
    iso3: "NAM",
    iso4: null,
    isoNum: "516",
    name: { FRA: "Namibie" },
  },
  {
    obsolete: false,
    iso2: "NR",
    iso3: "NRU",
    iso4: null,
    isoNum: "520",
    name: { FRA: "Nauru" },
  },
  {
    obsolete: false,
    iso2: "NP",
    iso3: "NPL",
    iso4: null,
    isoNum: "524",
    name: { FRA: "Népal" },
  },
  {
    obsolete: false,
    iso2: "NI",
    iso3: "NIC",
    iso4: null,
    isoNum: "558",
    name: { FRA: "Nicaragua" },
  },
  {
    obsolete: false,
    iso2: "NE",
    iso3: "NER",
    iso4: null,
    isoNum: "562",
    name: { FRA: "Niger" },
  },
  {
    obsolete: false,
    iso2: "NG",
    iso3: "NGA",
    iso4: null,
    isoNum: "566",
    name: { FRA: "Nigeria" },
  },
  {
    obsolete: false,
    iso2: "NU",
    iso3: "NIU",
    iso4: null,
    isoNum: "570",
    name: { FRA: "Niue" },
  },
  {
    obsolete: false,
    iso2: "NF",
    iso3: "NFK",
    iso4: null,
    isoNum: "574",
    name: { FRA: "Île Norfolk" },
  },
  {
    obsolete: false,
    iso2: "NO",
    iso3: "NOR",
    iso4: null,
    isoNum: "578",
    name: { FRA: "Norvège" },
  },
  {
    obsolete: false,
    iso2: "NC",
    iso3: "NCL",
    iso4: null,
    isoNum: "540",
    name: { FRA: "Nouvelle-Calédonie" },
  },
  {
    obsolete: false,
    iso2: "NZ",
    iso3: "NZL",
    iso4: null,
    isoNum: "554",
    name: { FRA: "Nouvelle-Zélande" },
  },
  {
    obsolete: true,
    iso2: "NH",
    iso3: "NHB",
    iso4: "NHVU",
    isoNum: "548",
    name: { FRA: "Nouvelles-Hébrides" },
  },
  {
    obsolete: false,
    iso2: "IO",
    iso3: "IOT",
    iso4: null,
    isoNum: "086",
    name: { FRA: "Territoire britannique de l'océan Indien" },
  },
  {
    obsolete: false,
    iso2: "OM",
    iso3: "OMN",
    iso4: null,
    isoNum: "512",
    name: { FRA: "Oman" },
  },
  {
    obsolete: false,
    iso2: "UG",
    iso3: "UGA",
    iso4: null,
    isoNum: "800",
    name: { FRA: "Ouganda" },
  },
  {
    obsolete: false,
    iso2: "UZ",
    iso3: "UZB",
    iso4: null,
    isoNum: "860",
    name: { FRA: "Ouzbékistan" },
  },
  {
    obsolete: false,
    iso2: "PK",
    iso3: "PAK",
    iso4: null,
    isoNum: "586",
    name: { FRA: "Pakistan" },
  },
  {
    obsolete: false,
    iso2: "PW",
    iso3: "PLW",
    iso4: null,
    isoNum: "585",
    name: { FRA: "Palaos" },
  },
  {
    obsolete: false,
    iso2: "PA",
    iso3: "PAN",
    iso4: null,
    isoNum: "591",
    name: { FRA: "Panama" },
  },
  {
    obsolete: false,
    iso2: "PG",
    iso3: "PNG",
    iso4: null,
    isoNum: "598",
    name: { FRA: "Papouasie Nouvelle Guinée" },
  },
  {
    obsolete: false,
    iso2: "PY",
    iso3: "PRY",
    iso4: null,
    isoNum: "600",
    name: { FRA: "Paraguay" },
  },
  {
    obsolete: false,
    iso2: "NL",
    iso3: "NLD",
    iso4: null,
    isoNum: "528",
    name: { FRA: "Pays-Bas" },
  },
  {
    obsolete: false,
    iso2: "PE",
    iso3: "PER",
    iso4: null,
    isoNum: "604",
    name: { FRA: "Pérou" },
  },
  {
    obsolete: false,
    iso2: "PH",
    iso3: "PHL",
    iso4: null,
    isoNum: "608",
    name: { FRA: "Philippines" },
  },
  {
    obsolete: false,
    iso2: "PN",
    iso3: "PCN",
    iso4: null,
    isoNum: "612",
    name: { FRA: "Îles Pitcairn" },
  },
  {
    obsolete: false,
    iso2: "PL",
    iso3: "POL",
    iso4: null,
    isoNum: "616",
    name: { FRA: "Pologne" },
  },
  {
    obsolete: false,
    iso2: "PF",
    iso3: "PYF",
    iso4: null,
    isoNum: "258",
    name: { FRA: "Polynésie française" },
  },
  {
    obsolete: false,
    iso2: "PR",
    iso3: "PRI",
    iso4: null,
    isoNum: "630",
    name: { FRA: "Porto Rico" },
  },
  {
    obsolete: false,
    iso2: "PT",
    iso3: "PRT",
    iso4: null,
    isoNum: "620",
    name: { FRA: "Portugal" },
  },
  {
    obsolete: false,
    iso2: "QA",
    iso3: "QAT",
    iso4: null,
    isoNum: "634",
    name: { FRA: "Qatar" },
  },
  {
    obsolete: false,
    iso2: "MK",
    iso3: "MKD",
    iso4: null,
    isoNum: "807",
    name: { FRA: "Macédoine du Nord" },
  },
  {
    obsolete: false,
    iso2: "RE",
    iso3: "REU",
    iso4: null,
    isoNum: "638",
    name: { FRA: "Réunion" },
  },
  {
    obsolete: true,
    iso2: "RH",
    iso3: "RHO",
    iso4: "RHZW",
    isoNum: "716",
    name: { FRA: "Rhodésie du Sud" },
  },
  {
    obsolete: false,
    iso2: "RO",
    iso3: "ROU",
    iso4: null,
    isoNum: "642",
    name: { FRA: "Roumanie" },
  },
  {
    obsolete: false,
    iso2: "GB",
    iso3: "GBR",
    iso4: null,
    isoNum: "826",
    name: { FRA: "Royaume-Uni" },
  },
  {
    obsolete: false,
    iso2: "RU",
    iso3: "RUS",
    iso4: null,
    isoNum: "643",
    name: { FRA: "Russie" },
  },
  {
    obsolete: false,
    iso2: "RW",
    iso3: "RWA",
    iso4: null,
    isoNum: "646",
    name: { FRA: "Rwanda" },
  },
  {
    obsolete: false,
    iso2: "EH",
    iso3: "ESH",
    iso4: null,
    isoNum: "732",
    name: { FRA: "Sahara occidental" },
  },
  {
    obsolete: false,
    iso2: "BL",
    iso3: "BLM",
    iso4: null,
    isoNum: "652",
    name: { FRA: "Saint-Barthélemy" },
  },
  {
    obsolete: false,
    iso2: "KN",
    iso3: "KNA",
    iso4: null,
    isoNum: "659",
    name: { FRA: "Saint-Christophe et Niévès" },
  },
  {
    obsolete: false,
    iso2: "SM",
    iso3: "SMR",
    iso4: null,
    isoNum: "674",
    name: { FRA: "Saint-Marin" },
  },
  {
    obsolete: false,
    iso2: "MF",
    iso3: "MAF",
    iso4: null,
    isoNum: "663",
    name: { FRA: "Saint-Martin" },
  },
  {
    obsolete: false,
    iso2: "SX",
    iso3: "SXM",
    iso4: null,
    isoNum: "534",
    name: { FRA: "Sint Maarten" },
  },
  {
    obsolete: false,
    iso2: "PM",
    iso3: "SPM",
    iso4: null,
    isoNum: "666",
    name: { FRA: "Saint-Pierre et Miquelon" },
  },
  {
    obsolete: false,
    iso2: "VA",
    iso3: "VAT",
    iso4: null,
    isoNum: "336",
    name: { FRA: "Saint-Siège" },
  },
  {
    obsolete: false,
    iso2: "VC",
    iso3: "VCT",
    iso4: null,
    isoNum: "670",
    name: { FRA: "Saint-Vincent et les Grenadines" },
  },
  {
    obsolete: false,
    iso2: "SH",
    iso3: "SHN",
    iso4: null,
    isoNum: "654",
    name: { FRA: "Sainte-Hélène, Ascension et Tristan da Cunha" },
  },
  {
    obsolete: false,
    iso2: "LC",
    iso3: "LCA",
    iso4: null,
    isoNum: "662",
    name: { FRA: "Sainte-Lucie" },
  },
  {
    obsolete: false,
    iso2: "SB",
    iso3: "SLB",
    iso4: null,
    isoNum: "090",
    name: { FRA: "Salomon" },
  },
  {
    obsolete: false,
    iso2: "WS",
    iso3: "WSM",
    iso4: null,
    isoNum: "882",
    name: { FRA: "Samoa" },
  },
  {
    obsolete: false,
    iso2: "AS",
    iso3: "ASM",
    iso4: null,
    isoNum: "016",
    name: { FRA: "Samoa américaines" },
  },
  {
    obsolete: false,
    iso2: "ST",
    iso3: "STP",
    iso4: null,
    isoNum: "678",
    name: { FRA: "Sao Tomé-et-Principe" },
  },
  {
    obsolete: false,
    iso2: "SN",
    iso3: "SEN",
    iso4: null,
    isoNum: "686",
    name: { FRA: "Sénégal" },
  },
  {
    obsolete: false,
    iso2: "RS",
    iso3: "SRB",
    iso4: null,
    isoNum: "688",
    name: { FRA: "Serbie" },
  },
  {
    obsolete: true,
    iso2: "CS",
    iso3: "SCG",
    iso4: "CSXX",
    isoNum: "891",
    name: { FRA: "Serbie-et-Monténégro" },
  },
  {
    obsolete: false,
    iso2: "SC",
    iso3: "SYC",
    iso4: null,
    isoNum: "690",
    name: { FRA: "Seychelles" },
  },
  {
    obsolete: false,
    iso2: "SL",
    iso3: "SLE",
    iso4: null,
    isoNum: "694",
    name: { FRA: "Sierra Leone" },
  },
  {
    obsolete: false,
    iso2: "SG",
    iso3: "SGP",
    iso4: null,
    isoNum: "702",
    name: { FRA: "Singapour" },
  },
  {
    obsolete: false,
    iso2: "SK",
    iso3: "SVK",
    iso4: null,
    isoNum: "703",
    name: { FRA: "Slovaquie" },
  },
  {
    obsolete: false,
    iso2: "SI",
    iso3: "SVN",
    iso4: null,
    isoNum: "705",
    name: { FRA: "Slovénie" },
  },
  {
    obsolete: false,
    iso2: "SO",
    iso3: "SOM",
    iso4: null,
    isoNum: "706",
    name: { FRA: "Somalie" },
  },
  {
    obsolete: false,
    iso2: "SD",
    iso3: "SDN",
    iso4: null,
    isoNum: "729",
    name: { FRA: "Soudan" },
  },
  {
    obsolete: false,
    iso2: "SS",
    iso3: "SSD",
    iso4: null,
    isoNum: "728",
    name: { FRA: "Soudan du Sud" },
  },
  {
    obsolete: false,
    iso2: "LK",
    iso3: "LKA",
    iso4: null,
    isoNum: "144",
    name: { FRA: "Sri Lanka" },
  },
  {
    obsolete: false,
    iso2: "SE",
    iso3: "SWE",
    iso4: null,
    isoNum: "752",
    name: { FRA: "Suède" },
  },
  {
    obsolete: false,
    iso2: "CH",
    iso3: "CHE",
    iso4: null,
    isoNum: "756",
    name: { FRA: "Suisse" },
  },
  {
    obsolete: false,
    iso2: "SR",
    iso3: "SUR",
    iso4: null,
    isoNum: "740",
    name: { FRA: "Suriname" },
  },
  {
    obsolete: false,
    iso2: "SJ",
    iso3: "SJM",
    iso4: null,
    isoNum: "744",
    name: { FRA: "Svalbard et ile Jan Mayen" },
  },
  {
    obsolete: false,
    iso2: "SY",
    iso3: "SYR",
    iso4: null,
    isoNum: "760",
    name: { FRA: "Syrie" },
  },
  {
    obsolete: false,
    iso2: "TJ",
    iso3: "TJK",
    iso4: null,
    isoNum: "762",
    name: { FRA: "Tadjikistan" },
  },
  {
    obsolete: false,
    iso2: "TW",
    iso3: "TWN",
    iso4: null,
    isoNum: "158",
    name: { FRA: "Taïwan" },
  },
  {
    obsolete: false,
    iso2: "TZ",
    iso3: "TZA",
    iso4: null,
    isoNum: "834",
    name: { FRA: "Tanzanie" },
  },
  {
    obsolete: false,
    iso2: "TD",
    iso3: "TCD",
    iso4: null,
    isoNum: "148",
    name: { FRA: "Tchad" },
  },
  {
    obsolete: true,
    iso2: "CS",
    iso3: "CSK",
    iso4: "CSHH",
    isoNum: "200",
    name: { FRA: "Tchécoslovaquie" },
  },
  {
    obsolete: false,
    iso2: "CZ",
    iso3: "CZE",
    iso4: null,
    isoNum: "203",
    name: { FRA: "Tchéquie" },
  },
  {
    obsolete: false,
    iso2: "TF",
    iso3: "ATF",
    iso4: null,
    isoNum: "260",
    name: { FRA: "Terres australes et antarctiques françaises" },
  },
  {
    obsolete: false,
    iso2: "TH",
    iso3: "THA",
    iso4: null,
    isoNum: "764",
    name: { FRA: "Thaïlande" },
  },
  {
    obsolete: false,
    iso2: "TL",
    iso3: "TLS",
    iso4: null,
    isoNum: "626",
    name: { FRA: "Timor-Leste" },
  },
  {
    obsolete: true,
    iso2: "TP",
    iso3: "TMP",
    iso4: "TPTL",
    isoNum: "626",
    name: { FRA: "Timor oriental" },
  },
  {
    obsolete: false,
    iso2: "TG",
    iso3: "TGO",
    iso4: null,
    isoNum: "768",
    name: { FRA: "Togo" },
  },
  {
    obsolete: false,
    iso2: "TK",
    iso3: "TKL",
    iso4: null,
    isoNum: "772",
    name: { FRA: "Tokelau" },
  },
  {
    obsolete: false,
    iso2: "TO",
    iso3: "TON",
    iso4: null,
    isoNum: "776",
    name: { FRA: "Tonga" },
  },
  {
    obsolete: false,
    iso2: "TT",
    iso3: "TTO",
    iso4: null,
    isoNum: "780",
    name: { FRA: "Trinité-et-Tobago" },
  },
  {
    obsolete: false,
    iso2: "TN",
    iso3: "TUN",
    iso4: null,
    isoNum: "788",
    name: { FRA: "Tunisie" },
  },
  {
    obsolete: false,
    iso2: "TR",
    iso3: "TUR",
    iso4: null,
    isoNum: "792",
    name: { FRA: "Turquie" },
  },
  {
    obsolete: false,
    iso2: "TM",
    iso3: "TKM",
    iso4: null,
    isoNum: "795",
    name: { FRA: "Turkménistan" },
  },
  {
    obsolete: false,
    iso2: "TC",
    iso3: "TCA",
    iso4: null,
    isoNum: "796",
    name: { FRA: "Îles Turques et Caïques" },
  },
  {
    obsolete: false,
    iso2: "TV",
    iso3: "TUV",
    iso4: null,
    isoNum: "798",
    name: { FRA: "Tuvalu" },
  },
  {
    obsolete: false,
    iso2: "UA",
    iso3: "UKR",
    iso4: null,
    isoNum: "804",
    name: { FRA: "Ukraine" },
  },
  {
    obsolete: true,
    iso2: "SU",
    iso3: "SUN",
    iso4: "SUHH",
    isoNum: "810",
    name: { FRA: "Union des républiques socialistes soviétiques" },
  },
  {
    obsolete: false,
    iso2: "UY",
    iso3: "URY",
    iso4: null,
    isoNum: "858",
    name: { FRA: "Uruguay" },
  },
  {
    obsolete: false,
    iso2: "VU",
    iso3: "VUT",
    iso4: null,
    isoNum: "548",
    name: { FRA: "Vanuatu" },
  },
  {
    obsolete: false,
    iso2: "VE",
    iso3: "VEN",
    iso4: null,
    isoNum: "862",
    name: { FRA: "Venezuela" },
  },
  {
    obsolete: false,
    iso2: "VN",
    iso3: "VNM",
    iso4: null,
    isoNum: "704",
    name: { FRA: "Viêt Nam" },
  },
  {
    obsolete: false,
    iso2: "WF",
    iso3: "WLF",
    iso4: null,
    isoNum: "876",
    name: { FRA: "Wallis et Futuna" },
  },
  {
    obsolete: false,
    iso2: "YE",
    iso3: "YEM",
    iso4: null,
    isoNum: "887",
    name: { FRA: "Yémen" },
  },
  {
    obsolete: true,
    iso2: "YD",
    iso3: "YMD",
    iso4: "YDYE",
    isoNum: "720",
    name: { FRA: "Yémen démocratique" },
  },
  {
    obsolete: true,
    iso2: "YU",
    iso3: "YUG",
    iso4: "YUCS",
    isoNum: "891",
    name: { FRA: "Yougoslavie" },
  },
  {
    obsolete: true,
    iso2: "ZR",
    iso3: "ZAR",
    iso4: "ZRCD",
    isoNum: "180",
    name: { FRA: "Zaïre" },
  },
  {
    obsolete: false,
    iso2: "ZM",
    iso3: "ZMB",
    iso4: null,
    isoNum: "894",
    name: { FRA: "Zambie" },
  },
  {
    obsolete: false,
    iso2: "ZW",
    iso3: "ZWE",
    iso4: null,
    isoNum: "716",
    name: { FRA: "Zimbabwe" },
  },
] as const satisfies {
  obsolete: boolean
  iso2: string;
  iso3: string;
  iso4: string | null;
  isoNum: string | null;
  name: { FRA: string }
}[];
